export const APP_CONFIG = {
  APP_NAME: "SOS Guardian",
  APP_VERSION: "1.0.0",
  MAX_EMERGENCY_CONTACTS: 10,
  DEFAULT_SAFETY_TIMER: 30,
  SAFETY_TIMER_OPTIONS: [15, 30, 45, 60, 90, 120],
  LOCATION_UPDATE_INTERVAL: 5000,
  FUNCTIONS_BASE_URL: "https://us-central1-sos-guardian-6b650.cloudfunctions.net",
  OPENCAGE_API_KEY: "YOUR_OPENCAGE_API_KEY",
} as const;

